export const SELECTABLE_AGENTS = [
  { id: 'protein', name: 'Protein Agent', role: 'Protein Agent', icon: '💪', shortDescription: 'Prioritizes filling, protein-rich recipes.', focus: 'protein density, satiety, eggs, paneer, dal, legumes, soy, dairy', debateStyle: 'Direct and practical. Pushes for meals that are filling and protein-forward.', loadingLine: 'Protein Agent is checking what will keep you full.', colorTheme: 'purple', color: 'bg-indigo-100 text-indigo-800' },
  { id: 'nutrition', name: 'Nutrition Agent', role: 'Nutrition Agent', icon: '🥦', shortDescription: 'Checks overall balance and meal quality.', focus: 'vegetables, fiber, balance, lightness, completeness, not making meals too oily or carb-heavy', debateStyle: 'Calm and balanced. Looks for sensible, well-rounded meals.', loadingLine: 'Nutrition Agent is balancing the plate.', colorTheme: 'green', color: 'bg-emerald-100 text-emerald-800' },
  { id: 'fusion', name: 'Fusion Agent', role: 'Fusion Agent', icon: '🌍', shortDescription: 'Suggests creative twists using available ingredients.', focus: 'creative combinations, rice bowls, wraps, stir-fries, global formats, non-boring variations', debateStyle: 'Creative but grounded. Suggests interesting versions without requiring rare ingredients.', loadingLine: 'Fusion Agent is looking for a creative twist.', colorTheme: 'indigo', color: 'bg-sky-100 text-sky-800' },
  { id: 'time', name: 'Time Agent', role: 'Time Agent', icon: '⚡', shortDescription: 'Keeps recipes quick and realistic.', focus: 'speed, fewer steps, less chopping, simple cooking, practical time limits', debateStyle: 'Short and efficient. Rejects recipes that are too slow or fussy.', loadingLine: 'Time Agent is racing the clock.', colorTheme: 'yellow', color: 'bg-yellow-100 text-yellow-800' },
  { id: 'taste', name: 'Taste Agent', role: 'Taste Agent', icon: '🌶️', shortDescription: 'Protects flavor, texture, and enjoyment.', focus: 'flavor, spice, texture, tadka, contrast, avoiding bland food', debateStyle: 'Expressive but useful. Pushes for recipes that will actually taste good.', loadingLine: 'Taste Agent is checking for flavor.', colorTheme: 'red', color: 'bg-rose-100 text-rose-800' },
] as const

export const MODERATOR = { id: 'moderator', name: 'Cabinet Moderator', role: 'Final Moderator', icon: '👨‍🍳', shortDescription: 'Summarizes the agent debate and selects the final recommendations.', focus: 'practical home cooking, feasibility, trade-offs, and clear final decisions', debateStyle: 'Clear, concise, and balanced.', loadingLine: 'Cabinet Moderator is calling the vote.', colorTheme: 'charcoal', color: 'bg-slate-100 text-slate-800' } as const

export type AgentConfig = typeof SELECTABLE_AGENTS[number]
export type ModeratorConfig = typeof MODERATOR
